Web/lampisite/lampi/urls.py
from django.urls import path, re_path

from . import views

app_name = 'lampi'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.AddLampiView.as_view(), name='add'),
    re_path(r'^device/(?P<device_id>[0-9a-fA-F]+)$',
            views.DetailView.as_view(), name='detail'),
]

Web/lampisite/lampisite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.conf import settings

extra_context = {}

urlpatterns = [
    path('lampi/', include('lampi.urls'), name='lampi'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(
         template_name='lampi/login.html',
         extra_context=extra_context), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
          template_name='lampi/logout.html',
         extra_context=extra_context), name='logout'),
    path('', RedirectView.as_view(pattern_name='lampi:index'), name='root'),
]

Web/lampisite/lampi/models.py
from django.db import models
from django.contrib.auth.models import User
from uuid import uuid4
import json
import paho.mqtt.publish

# Create your models here.
DEFAULT_USER = 'parked_device_user'


def get_parked_user():
    return get_user_model().objects.get_or_create(username=DEFAULT_USER)[0]


def generate_association_code():
    return uuid4().hex


class Lampi(models.Model):
    name = models.CharField(max_length=50, default="My LAMPI")
    device_id = models.CharField(max_length=12, primary_key=True)
    user = models.ForeignKey(User,
                             on_delete=models.SET(get_parked_user))
    association_code = models.CharField(max_length=32, unique=True,
                                        default=generate_association_code)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}: {}".format(self.device_id, self.name)

    def _generate_device_association_topic(self):
        return 'devices/{}/lamp/associated'.format(self.device_id)

    def publish_unassociated_msg(self):
        # send association MQTT message
        assoc_msg = {}
        assoc_msg['associated'] = False
        assoc_msg['code'] = self.association_code
        paho.mqtt.publish.single(
            self._generate_device_association_topic(),
            json.dumps(assoc_msg),
            qos=2,
            retain=True,
            hostname="localhost",
            port=50001,
            )

    def associate_and_publish_associated_msg(self,  user):
        # update Lampi instance with new user
        self.user = user
        self.save()
        # publish associated message
        assoc_msg = {}
        assoc_msg['associated'] = True
        paho.mqtt.publish.single(
            self._generate_device_association_topic(),
            json.dumps(assoc_msg),
            qos=2,
            retain=True,
            hostname="localhost",
            port=50001,
            )

Web/lampisite/lampi/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.conf import settings
from .models import Lampi


def device_association_topic(device_id):
    return 'devices/{}/lamp/associated'.format(device_id)


class AddLampiForm(forms.Form):
    association_code = forms.CharField(label="Association Code", min_length=6,
                                       max_length=6)

    def clean(self):
        cleaned_data = super(AddLampiForm, self).clean()
        print("received form with code {}".format(
              cleaned_data['association_code']))
        # look up device with start of association_code
        uname = settings.DEFAULT_USER
        parked_user = get_user_model().objects.get(username=uname)
        devices = Lampi.objects.filter(
            user=parked_user,
            association_code__startswith=cleaned_data['association_code'])
        if not devices:
            self.add_error('association_code',
                           ValidationError("Invalid Association Code",
                                           code='invalid'))
        else:
            cleaned_data['device'] = devices[0]
        return cleaned_data

Web/lampisite/lampi/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from .models import Lampi
from django.conf import settings
from lampi.forms import AddLampiForm
from mixpanel import Mixpanel


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'lampi/index.html'

    def get_queryset(self):
        results = Lampi.objects.filter(user=self.request.user)
        return results

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['MIXPANEL_TOKEN'] = settings.MIXPANEL_TOKEN
        return context


class DetailView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'lampi/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['device'] = get_object_or_404(
            Lampi, pk=kwargs['device_id'], user=self.request.user)
        context['MIXPANEL_TOKEN'] = settings.MIXPANEL_TOKEN
        return context


class AddLampiView(LoginRequiredMixin, generic.FormView):
    template_name = 'lampi/addlampi.html'
    form_class = AddLampiForm
    success_url = '/lampi'

    def get_context_data(self, **kwargs):
        context = super(AddLampiView, self).get_context_data(**kwargs)
        context['MIXPANEL_TOKEN'] = settings.MIXPANEL_TOKEN
        return context

    def form_valid(self, form):
        device = form.cleaned_data['device']
        device.associate_and_publish_associated_msg(self.request.user)

        mp = Mixpanel(settings.MIXPANEL_TOKEN)
        mp.track(device.user.username, "LAMPI Activation",
                 {'event_type': 'activations', 'interface': 'web',
                  'device_id': device.device_id})

        return super(AddLampiView, self).form_valid(form)

Web/lampisite/lampi/templates/lampi/addlampi.html
{% extends "lampi/base.html" %}

{% block title %}Add LAMPI{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add LAMPI" />
</form>
{% endblock %}

{% block page_event %}Add LAMPI{% endblock %}

Web/lampisite/lampi/templates/lampi/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}LAMPI{% endblock %}</title>

  <meta charset="utf-8">
  <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">

  <link rel="stylesheet" type="text/css" href="{% static 'lampi/css/site.css' %}"/>

<script>(function(f,b){if(!b.__SV){var e,g,i,h;window.mixpanel=b;b._i=[];b.init=function(e,f,c){function g(a,d){var b=d.split(".");2==b.length&&(a=a[b[0]],d=b[1]);a[d]=function(){a.push([d].concat(Array.prototype.slice.call(arguments,0)))}}var a=b;"undefined"!==typeof c?a=b[c]=[]:c="mixpanel";a.people=a.people||[];a.toString=function(a){var d="mixpanel";"mixpanel"!==c&&(d+="."+c);a||(d+=" (stub)");return d};a.people.toString=function(){return a.toString(1)+".people (stub)"};i="disable time_event track track_pageview track_links track_forms track_with_groups add_group set_group remove_group register register_once alias unregister identify name_tag set_config reset opt_in_tracking opt_out_tracking has_opted_in_tracking has_opted_out_tracking clear_opt_in_out_tracking start_batch_senders people.set people.set_once people.unset people.increment people.append people.union people.track_charge people.clear_charges people.delete_user people.remove".split(" ");
for(h=0;h<i.length;h++)g(a,i[h]);var j="set set_once union unset remove delete".split(" ");a.get_group=function(){function b(c){d[c]=function(){call2_args=arguments;call2=[c].concat(Array.prototype.slice.call(call2_args,0));a.push([e,call2])}}for(var d={},e=["get_group"].concat(Array.prototype.slice.call(arguments,0)),c=0;c<j.length;c++)b(j[c]);return d};b._i.push([e,f,c])};b.__SV=1.2;e=f.createElement("script");e.type="text/javascript";e.async=!0;e.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?
MIXPANEL_CUSTOM_LIB_URL:"file:"===f.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";g=f.getElementsByTagName("script")[0];g.parentNode.insertBefore(e,g)}})(document,window.mixpanel||[]);
	mixpanel.init("{{ MIXPANEL_TOKEN }}", {batch_requests: true, cross_subdomain_cookie: false});

    mixpanel.register({"interface": "web"});
</script>

    {% block additional_head_content %}
    {% endblock %}

</head>
<body>
    <div id="outer-pane" class="centered-root">
         <div>
            {% if user.is_authenticated %}
		<form action="{% url 'logout' %}" method="post">
		    {% csrf_token %}
		    <button type="submit" class="btn-link">Logout</button>
		</form>
               {% if user.is_superuser %}
                   <a href="{% url 'admin:index' %}">Admin</a>
               {% endif %}
            {% else %}
               <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
        {% block content %}
        <p>Content Goes Here.</p>
        {% endblock %}
    </div>
    <script>
        mixpanel.track("{% block page_event %}Page View{% endblock %}", {"event_type": "pageview"});
    </script>
</body>
</html>

Web/lampisite/lampi/templates/lampi/detail.html
{% extends "lampi/base.html" %}
{% load static %}

{% block title %}LAMPI{% endblock %}

{% block additional_head_content %}
  <meta name="description" content="LAMPI Control for {{ device.device_id }}">
  <link rel="stylesheet" type="text/css"
         href="{% static 'lampi/css/lampi-sliders.css' %}">


  <style id="saturation-slider-style" type="text/css"></style>
  <style id="hue-thumb-style" type="text/css"></style>
  <style id="brightness-thumb-style" type="text/css"></style>
  <style id="saturation-thumb-style" type="text/css"></style>
{% endblock %}

{% block content %}
    <script type="text/javascript">
        var window_global = {};
        window_global['device_id'] = "{{ device.device_id }}";
        window_global['mqtt'] = {'hostname': window.location.hostname,
                                'websockets_port': 50002};
    </script>
		<div id="top-pane">
			<div id="sliders">
				<input id="hue-slider" class="hue slider" type="range" min="0.0" max="1.0" step="0.01"></input>
				<input id="saturation-slider" class="saturation slider" type="range" min="0.0" max="1.0" step="0.01"></input>
				<input id="brightness-slider" class="brightness slider" type="range" min="0.0" max="1.0" step="0.01"></input>
			</div>
		</div>
		<div id="colorbox"></div>
		<div id="bottom-pane">
			<div class="toggle-button" id="power"></div>
		</div>
	</div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.2/mqttws31.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70/jquery.blockUI.min.js" type="text/javascript"></script>

    <script src="{% static 'lampi/js/tinycolor.js' %}" type="text/javascript"></script>
    <script src="{% static 'lampi/js/lampi.js' %}" type="text/javascript"></script>
    <script src="{% static 'lampi/js/lampi-sliders.js' %}" type="text/javascript"></script>

{% endblock %}

{% block page_event %}LAMPI Detail{% endblock %}

Web/lampisite/lampi/templates/lampi/index.html
{% extends "lampi/base.html" %}

{% block content %}

{% if lampi_list %}
    <ul>
    {% for device in lampi_list %}
       <li><a href="{% url 'lampi:detail' device.device_id %}">
        {{ device.name }} {{device.device_id }}</a></li>
    {% endfor %}
    </ul>
    <a href="{% url 'lampi:add' %}">Add a LAMPI Device</a>
{% else %}
    <p>No devices are available.</p>
    <a href="{% url 'lampi:add' %}">Add a LAMPI Device</a>
{% endif %}

{% endblock %}

{% block page_event %}LAMPI List{% endblock %}

Web/lampisite/lampi/templates/lampi/login.html
{% extends "lampi/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

Web/lampisite/lampi/templates/lampi/logout.html
{% extends "lampi/base.html" %}

{% block title %}Logged Out{% endblock %}

{% block content %}
  <p>Logged out</p>
{% endblock %}